const data = [
  {
    languageName: "Afrikaans (South Africa) Female",
    languageCode: "af-ZA",
    voiceCode: "af-ZA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Afrikaans (South Africa) Male",
    languageCode: "af-ZA",
    voiceCode: "af-ZA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Amharic (Ethiopia) Male",
    languageCode: "am-ET",
    voiceCode: "am-ET-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Amharic (Ethiopia) Female",
    languageCode: "am-ET",
    voiceCode: "am-ET-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (United Arab Emirates) Female",
    languageCode: "ar-AE",
    voiceCode: "ar-AE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (United Arab Emirates) Male",
    languageCode: "ar-AE",
    voiceCode: "ar-AE-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Bahrain) Male",
    languageCode: "ar-BH",
    voiceCode: "ar-BH-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Bahrain) Female",
    languageCode: "ar-BH",
    voiceCode: "ar-BH-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Algeria) Female",
    languageCode: "ar-DZ",
    voiceCode: "ar-DZ-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Algeria) Male",
    languageCode: "ar-DZ",
    voiceCode: "ar-DZ-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Egypt) Female",
    languageCode: "ar-EG",
    voiceCode: "ar-EG-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Egypt) Male",
    languageCode: "ar-EG",
    voiceCode: "ar-EG-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Egypt) Standard Female",
    languageCode: "ar-EG",
    voiceCode: "ar-EG-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Iraq) Male",
    languageCode: "ar-IQ",
    voiceCode: "ar-IQ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Iraq) Female",
    languageCode: "ar-IQ",
    voiceCode: "ar-IQ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Jordan) Female",
    languageCode: "ar-JO",
    voiceCode: "ar-JO-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Jordan) Male",
    languageCode: "ar-JO",
    voiceCode: "ar-JO-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Kuwait) Male",
    languageCode: "ar-KW",
    voiceCode: "ar-KW-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Kuwait) Female",
    languageCode: "ar-KW",
    voiceCode: "ar-KW-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Libya) Female",
    languageCode: "ar-LY",
    voiceCode: "ar-LY-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Libya) Male",
    languageCode: "ar-LY",
    voiceCode: "ar-LY-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Morocco) Male",
    languageCode: "ar-MA",
    voiceCode: "ar-MA-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Morocco) Female",
    languageCode: "ar-MA",
    voiceCode: "ar-MA-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Qatar) Female",
    languageCode: "ar-QA",
    voiceCode: "ar-QA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Qatar) Male",
    languageCode: "ar-QA",
    voiceCode: "ar-QA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Saudi Arabia) Male",
    languageCode: "ar-SA",
    voiceCode: "ar-SA-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Saudi Arabia) Female",
    languageCode: "ar-SA",
    voiceCode: "ar-SA-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Saudi Arabia) Standard Male",
    languageCode: "ar-SA",
    voiceCode: "ar-SA-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Syria) Female",
    languageCode: "ar-SY",
    voiceCode: "ar-SY-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Syria) Male",
    languageCode: "ar-SY",
    voiceCode: "ar-SY-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Tunisia) Male",
    languageCode: "ar-TN",
    voiceCode: "ar-TN-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Tunisia) Female",
    languageCode: "ar-TN",
    voiceCode: "ar-TN-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Yemen) Female",
    languageCode: "ar-YE",
    voiceCode: "ar-YE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Bulgarian (Bulgaria) Male",
    languageCode: "bg-BG",
    voiceCode: "bg-BG-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Bulgarian (Bulgaria) Female",
    languageCode: "bg-BG",
    voiceCode: "bg-BG-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Bulgarian (Bulgaria) Male",
    languageCode: "bg-BG",
    voiceCode: "bg-BG-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Bangla (Bangladesh) Female",
    languageCode: "bn-BD",
    voiceCode: "bn-BD-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Bangla (Bangladesh) Male",
    languageCode: "bn-BD",
    voiceCode: "bn-BD-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Catalan (Spain) Female",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Catalan (Spain) Female",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Catalan (Spain) Male",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Catalan (Spain) Female",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Czech (Czech) Male",
    languageCode: "cs-CZ",
    voiceCode: "cs-CZ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Czech (Czech) Female",
    languageCode: "cs-CZ",
    voiceCode: "cs-CZ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Czech (Czech) Male",
    languageCode: "cs-CZ",
    voiceCode: "cs-CZ-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Welsh (United Kingdom) Male",
    languageCode: "cy-GB",
    voiceCode: "cy-GB-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Welsh (United Kingdom) Female",
    languageCode: "cy-GB",
    voiceCode: "cy-GB-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Danish (Denmark) Female",
    languageCode: "da-DK",
    voiceCode: "da-DK-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Danish (Denmark) Male",
    languageCode: "da-DK",
    voiceCode: "da-DK-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Danish (Denmark) Female",
    languageCode: "da-DK",
    voiceCode: "da-DK-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "German (Austria) Female",
    languageCode: "de-AT",
    voiceCode: "de-AT-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "German (Austria) Male",
    languageCode: "de-AT",
    voiceCode: "de-AT-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "German (Austria) Standard Male",
    languageCode: "de-AT",
    voiceCode: "de-AT-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "German (Switzerland) Male",
    languageCode: "de-CH",
    voiceCode: "de-CH-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "German (Switzerland) Female",
    languageCode: "de-CH",
    voiceCode: "de-CH-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "German (Switzerland) Male",
    languageCode: "de-CH",
    voiceCode: "de-CH-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "German (Germany) Female",
    languageCode: "de-DE",
    voiceCode: "de-DE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "German (Germany) Male",
    languageCode: "de-DE",
    voiceCode: "de-DE-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "German (Germany) Female",
    languageCode: "de-DE",
    voiceCode: "de-DE-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "German (Germany) Male",
    languageCode: "de-DE",
    voiceCode: "de-DE-4",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Greek (Greece) Female",
    languageCode: "el-GR",
    voiceCode: "el-GR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Greek (Greece) Male",
    languageCode: "el-GR",
    voiceCode: "el-GR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Greek (Greece) Male",
    languageCode: "el-GR",
    voiceCode: "el-GR-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "English (Australia) Female",
    languageCode: "en-AU",
    voiceCode: "en-AU-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Australia) Male",
    languageCode: "en-AU",
    voiceCode: "en-AU-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Australia) Female",
    languageCode: "en-AU",
    voiceCode: "en-AU-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (Australia) Female",
    languageCode: "en-AU",
    voiceCode: "en-AU-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (Canada) Female",
    languageCode: "en-CA",
    voiceCode: "en-CA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Canada) Male",
    languageCode: "en-CA",
    voiceCode: "en-CA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Canada) Female",
    languageCode: "en-CA",
    voiceCode: "en-CA-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (Canada) Female",
    languageCode: "en-CA",
    voiceCode: "en-CA-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (United Kingdom) Female",
    languageCode: "en-GB",
    voiceCode: "en-GB-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United Kingdom) Male",
    languageCode: "en-GB",
    voiceCode: "en-GB-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (United Kingdom) Female",
    languageCode: "en-GB",
    voiceCode: "en-GB-3",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United Kingdom) Female",
    languageCode: "en-GB",
    voiceCode: "en-GB-4",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United Kingdom) Male",
    languageCode: "en-GB",
    voiceCode: "en-GB-5",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "English (United Kingdom) Female",
    languageCode: "en-GB",
    voiceCode: "en-GB-6",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (United Kingdom) Female",
    languageCode: "en-GB",
    voiceCode: "en-GB-7",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (Hongkong) Male",
    languageCode: "en-HK",
    voiceCode: "en-HK-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Hongkong) Female",
    languageCode: "en-HK",
    voiceCode: "en-HK-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Ireland) Male",
    languageCode: "en-IE",
    voiceCode: "en-IE-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Ireland) Female",
    languageCode: "en-IE",
    voiceCode: "en-IE-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Ireland) Male",
    languageCode: "en-IE",
    voiceCode: "en-IE-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "English (India) Female",
    languageCode: "en-IN",
    voiceCode: "en-IN-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (India) Male",
    languageCode: "en-IN",
    voiceCode: "en-IN-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (India) Female",
    languageCode: "en-IN",
    voiceCode: "en-IN-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (India) Female",
    languageCode: "en-IN",
    voiceCode: "en-IN-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (India) Male",
    languageCode: "en-IN",
    voiceCode: "en-IN-5",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "English (Kenya) Female",
    languageCode: "en-KE",
    voiceCode: "en-KE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Kenya) Male",
    languageCode: "en-KE",
    voiceCode: "en-KE-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Nigeria) Male",
    languageCode: "en-NG",
    voiceCode: "en-NG-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Nigeria) Female",
    languageCode: "en-NG",
    voiceCode: "en-NG-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (New Zealand) Male",
    languageCode: "en-NZ",
    voiceCode: "en-NZ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (New Zealand) Female",
    languageCode: "en-NZ",
    voiceCode: "en-NZ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Philippines) Male",
    languageCode: "en-PH",
    voiceCode: "en-PH-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Philippines) Female",
    languageCode: "en-PH",
    voiceCode: "en-PH-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Singapore) Female",
    languageCode: "en-SG",
    voiceCode: "en-SG-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (Singapore) Male",
    languageCode: "en-SG",
    voiceCode: "en-SG-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Tanzania) Male",
    languageCode: "en-TZ",
    voiceCode: "en-TZ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (Tanzania) Female",
    languageCode: "en-TZ",
    voiceCode: "en-TZ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Male",
    languageCode: "en-US",
    voiceCode: "en-US-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-4",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-5",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-6",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-7",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Male",
    languageCode: "en-US",
    voiceCode: "en-US-8",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (United States) Male",
    languageCode: "en-US",
    voiceCode: "en-US-9",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-10",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-11",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Male",
    languageCode: "en-US",
    voiceCode: "en-US-12",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (United States) Male",
    languageCode: "en-US",
    voiceCode: "en-US-13",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-14",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-15",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-16",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-17",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (United States) Male",
    languageCode: "en-US",
    voiceCode: "en-US-18",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "English (United States) Male",
    languageCode: "en-US",
    voiceCode: "en-US-19",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "English (United States) Female",
    languageCode: "en-US",
    voiceCode: "en-US-20",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "English (South Africa) Female",
    languageCode: "en-ZA",
    voiceCode: "en-ZA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "English (South Africa) Male",
    languageCode: "en-ZA",
    voiceCode: "en-ZA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Argentina) Female",
    languageCode: "es-AR",
    voiceCode: "es-AR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Argentina) Male",
    languageCode: "es-AR",
    voiceCode: "es-AR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Bolivia) Male",
    languageCode: "es-BO",
    voiceCode: "es-BO-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Bolivia) Female",
    languageCode: "es-BO",
    voiceCode: "es-BO-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Chile) Female",
    languageCode: "es-CL",
    voiceCode: "es-CL-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Chile) Male",
    languageCode: "es-CL",
    voiceCode: "es-CL-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Colombia) Male",
    languageCode: "es-CO",
    voiceCode: "es-CO-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Colombia) Female",
    languageCode: "es-CO",
    voiceCode: "es-CO-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Costa Rica) Male",
    languageCode: "es-CR",
    voiceCode: "es-CR-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Costa Rica) Female",
    languageCode: "es-CR",
    voiceCode: "es-CR-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Cuba) Female",
    languageCode: "es-CU",
    voiceCode: "es-CU-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Cuba) Male",
    languageCode: "es-CU",
    voiceCode: "es-CU-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Dominican Republic) Male",
    languageCode: "es-DO",
    voiceCode: "es-DO-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Dominican Republic) Female",
    languageCode: "es-DO",
    voiceCode: "es-DO-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Ecuador) Female",
    languageCode: "es-EC",
    voiceCode: "es-EC-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Ecuador) Male",
    languageCode: "es-EC",
    voiceCode: "es-EC-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Spain) Male",
    languageCode: "es-ES",
    voiceCode: "es-ES-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Spain) Female",
    languageCode: "es-ES",
    voiceCode: "es-ES-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Spain) Female",
    languageCode: "es-ES",
    voiceCode: "es-ES-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Spain) Female",
    languageCode: "es-ES",
    voiceCode: "es-ES-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Spain) Male",
    languageCode: "es-ES",
    voiceCode: "es-ES-5",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Equatorial Guinea) Male",
    languageCode: "es-GQ",
    voiceCode: "es-GQ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Equatorial Guinea) Female",
    languageCode: "es-GQ",
    voiceCode: "es-GQ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Guatemala) Male",
    languageCode: "es-GT",
    voiceCode: "es-GT-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Guatemala) Female",
    languageCode: "es-GT",
    voiceCode: "es-GT-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Honduras) Male",
    languageCode: "es-HN",
    voiceCode: "es-HN-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Honduras) Female",
    languageCode: "es-HN",
    voiceCode: "es-HN-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Mexico) Female",
    languageCode: "es-MX",
    voiceCode: "es-MX-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Mexico) Male",
    languageCode: "es-MX",
    voiceCode: "es-MX-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Mexico) Female",
    languageCode: "es-MX",
    voiceCode: "es-MX-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Mexico) Male",
    languageCode: "es-MX",
    voiceCode: "es-MX-4",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Nicaragua) Male",
    languageCode: "es-NI",
    voiceCode: "es-NI-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Nicaragua) Female",
    languageCode: "es-NI",
    voiceCode: "es-NI-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Panama) Female",
    languageCode: "es-PA",
    voiceCode: "es-PA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Panama) Male",
    languageCode: "es-PA",
    voiceCode: "es-PA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Peru) Male",
    languageCode: "es-PE",
    voiceCode: "es-PE-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Peru) Female",
    languageCode: "es-PE",
    voiceCode: "es-PE-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Puerto Rico) Female",
    languageCode: "es-PR",
    voiceCode: "es-PR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Puerto Rico) Male",
    languageCode: "es-PR",
    voiceCode: "es-PR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Paraguay) Male",
    languageCode: "es-PY",
    voiceCode: "es-PY-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Paraguay) Female",
    languageCode: "es-PY",
    voiceCode: "es-PY-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (El Salvador) Female",
    languageCode: "es-SV",
    voiceCode: "es-SV-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (El Salvador) Male",
    languageCode: "es-SV",
    voiceCode: "es-SV-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (United States) Male",
    languageCode: "es-US",
    voiceCode: "es-US-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (United States) Female",
    languageCode: "es-US",
    voiceCode: "es-US-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Uruguay) Male",
    languageCode: "es-UY",
    voiceCode: "es-UY-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Spanish (Uruguay) Female",
    languageCode: "es-UY",
    voiceCode: "es-UY-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Venezuela) Female",
    languageCode: "es-VE",
    voiceCode: "es-VE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Spanish (Venezuela) Male",
    languageCode: "es-VE",
    voiceCode: "es-VE-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Estonian (Estonia) Female",
    languageCode: "et-EE",
    voiceCode: "et-EE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Estonian (Estonia) Male",
    languageCode: "et-EE",
    voiceCode: "et-EE-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Persian (Iran) Female",
    languageCode: "fa-IR",
    voiceCode: "fa-IR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Persian (Iran) Male",
    languageCode: "fa-IR",
    voiceCode: "fa-IR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Finnish (Finland) Female",
    languageCode: "fi-FI",
    voiceCode: "fi-FI-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Finnish (Finland) Male",
    languageCode: "fi-FI",
    voiceCode: "fi-FI-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Finnish (Finland) Female",
    languageCode: "fi-FI",
    voiceCode: "fi-FI-3",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Finnish (Finland) Female",
    languageCode: "fi-FI",
    voiceCode: "fi-FI-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Filipino (Philippines) Male",
    languageCode: "fil-PH",
    voiceCode: "fil-PH-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Filipino (Philippines) Female",
    languageCode: "fil-PH",
    voiceCode: "fil-PH-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "French (Belgium) Female",
    languageCode: "fr-BE",
    voiceCode: "fr-BE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "French (Belgium) Male",
    languageCode: "fr-BE",
    voiceCode: "fr-BE-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "French (Canada) Female",
    languageCode: "fr-CA",
    voiceCode: "fr-CA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "French (Canada) Male",
    languageCode: "fr-CA",
    voiceCode: "fr-CA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "French (Canada) Male",
    languageCode: "fr-CA",
    voiceCode: "fr-CA-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "French (Canada) Female",
    languageCode: "fr-CA",
    voiceCode: "fr-CA-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "French (Canada) Female",
    languageCode: "fr-CA",
    voiceCode: "fr-CA-5",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "French (Switzerland) Female",
    languageCode: "fr-CH",
    voiceCode: "fr-CH-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "French (Switzerland) Male",
    languageCode: "fr-CH",
    voiceCode: "fr-CH-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "French (Switzerland) Male",
    languageCode: "fr-CH",
    voiceCode: "fr-CH-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "French (France) Female",
    languageCode: "fr-FR",
    voiceCode: "fr-FR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "French (France) Male",
    languageCode: "fr-FR",
    voiceCode: "fr-FR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "French (France) Female",
    languageCode: "fr-FR",
    voiceCode: "fr-FR-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "French (France) Female",
    languageCode: "fr-FR",
    voiceCode: "fr-FR-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "French (France) Male",
    languageCode: "fr-FR",
    voiceCode: "fr-FR-5",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Irish (Ireland) Male",
    languageCode: "ga-IE",
    voiceCode: "ga-IE-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Irish (Ireland) Female",
    languageCode: "ga-IE",
    voiceCode: "ga-IE-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Galician (Spain) Male",
    languageCode: "gl-ES",
    voiceCode: "gl-ES-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Galician (Spain) Female",
    languageCode: "gl-ES",
    voiceCode: "gl-ES-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Gujarati (India) Female",
    languageCode: "gu-IN",
    voiceCode: "gu-IN-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Gujarati (India) Male",
    languageCode: "gu-IN",
    voiceCode: "gu-IN-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Hebrew (Israel) Male",
    languageCode: "he-IL",
    voiceCode: "he-IL-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Hebrew (Israel) Female",
    languageCode: "he-IL",
    voiceCode: "he-IL-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Hebrew (Israel) Male",
    languageCode: "he-IL",
    voiceCode: "he-IL-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Hindi (India) Male",
    languageCode: "hi-IN",
    voiceCode: "hi-IN-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Hindi (India) Female",
    languageCode: "hi-IN",
    voiceCode: "hi-IN-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Hindi (India) Male",
    languageCode: "hi-IN",
    voiceCode: "hi-IN-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Hindi (India) Female",
    languageCode: "hi-IN",
    voiceCode: "hi-IN-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Croatian (Croatia) Female",
    languageCode: "hr-HR",
    voiceCode: "hr-HR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Croatian (Croatia) Male",
    languageCode: "hr-HR",
    voiceCode: "hr-HR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Croatian (Croatia) Male",
    languageCode: "hr-HR",
    voiceCode: "hr-HR-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Hungarian (Hungary) Female",
    languageCode: "hu-HU",
    voiceCode: "hu-HU-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Hungarian (Hungary) Male",
    languageCode: "hu-HU",
    voiceCode: "hu-HU-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Hungarian (Hungary) Male",
    languageCode: "hu-HU",
    voiceCode: "hu-HU-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Indonesian (Indonesia) Male",
    languageCode: "id-ID",
    voiceCode: "id-ID-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Indonesian (Indonesia) Female",
    languageCode: "id-ID",
    voiceCode: "id-ID-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Indonesian (Indonesia) Male",
    languageCode: "id-ID",
    voiceCode: "id-ID-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Italian (Italy) Female",
    languageCode: "it-IT",
    voiceCode: "it-IT-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Italian (Italy) Male",
    languageCode: "it-IT",
    voiceCode: "it-IT-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Italian (Italy) Female",
    languageCode: "it-IT",
    voiceCode: "it-IT-3",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Italian (Italy) Male",
    languageCode: "it-IT",
    voiceCode: "it-IT-4",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Italian (Italy) Female",
    languageCode: "it-IT",
    voiceCode: "it-IT-5",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Japanese (Japan) Female",
    languageCode: "ja-JP",
    voiceCode: "ja-JP-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Japanese (Japan) Male",
    languageCode: "ja-JP",
    voiceCode: "ja-JP-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Japanese (Japan) Female",
    languageCode: "ja-JP",
    voiceCode: "ja-JP-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Japanese (Japan) Female",
    languageCode: "ja-JP",
    voiceCode: "ja-JP-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Japanese (Japan) Male",
    languageCode: "ja-JP",
    voiceCode: "ja-JP-5",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Javanese (Indonesia) Male",
    languageCode: "jv-ID",
    voiceCode: "jv-ID-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Javanese (Indonesia) Female",
    languageCode: "jv-ID",
    voiceCode: "jv-ID-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Khmer (Cambodia) Male",
    languageCode: "km-KH",
    voiceCode: "km-KH-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Khmer (Cambodia) Female",
    languageCode: "km-KH",
    voiceCode: "km-KH-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Korean (Korea) Female",
    languageCode: "ko-KR",
    voiceCode: "ko-KR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Korean (Korea) Male",
    languageCode: "ko-KR",
    voiceCode: "ko-KR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Korean (Korea) Female",
    languageCode: "ko-KR",
    voiceCode: "ko-KR-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Lithuanian (Lithuania) Male",
    languageCode: "lt-LT",
    voiceCode: "lt-LT-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Lithuanian (Lithuania) Female",
    languageCode: "lt-LT",
    voiceCode: "lt-LT-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Latvian (Latvia) Female",
    languageCode: "lv-LV",
    voiceCode: "lv-LV-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Latvian (Latvia) Male",
    languageCode: "lv-LV",
    voiceCode: "lv-LV-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Marathi (India) Female",
    languageCode: "mr-IN",
    voiceCode: "mr-IN-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Marathi (India) Male",
    languageCode: "mr-IN",
    voiceCode: "mr-IN-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Malay (Malaysia) Male",
    languageCode: "ms-MY",
    voiceCode: "ms-MY-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Malay (Malaysia) Female",
    languageCode: "ms-MY",
    voiceCode: "ms-MY-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Malay (Malaysia) Male",
    languageCode: "ms-MY",
    voiceCode: "ms-MY-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Maltese (Malta) Female",
    languageCode: "mt-MT",
    voiceCode: "mt-MT-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Maltese (Malta) Male",
    languageCode: "mt-MT",
    voiceCode: "mt-MT-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Burmese (Myanmar) Female",
    languageCode: "my-MM",
    voiceCode: "my-MM-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Burmese (Myanmar) Male",
    languageCode: "my-MM",
    voiceCode: "my-MM-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Norwegian (Bokmål, Norway) Female",
    languageCode: "nb-NO",
    voiceCode: "nb-NO-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Norwegian (Bokmål, Norway) Male",
    languageCode: "nb-NO",
    voiceCode: "nb-NO-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Norwegian (Bokmål, Norway) Female",
    languageCode: "nb-NO",
    voiceCode: "nb-NO-3",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Norwegian (Bokmål, Norway) Female",
    languageCode: "nb-NO",
    voiceCode: "nb-NO-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Dutch (Belgium) Male",
    languageCode: "nl-BE",
    voiceCode: "nl-BE-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Dutch (Belgium) Female",
    languageCode: "nl-BE",
    voiceCode: "nl-BE-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Dutch (Netherlands) Female",
    languageCode: "nl-NL",
    voiceCode: "nl-NL-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Dutch (Netherlands) Female",
    languageCode: "nl-NL",
    voiceCode: "nl-NL-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Dutch (Netherlands) Male",
    languageCode: "nl-NL",
    voiceCode: "nl-NL-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Dutch (Netherlands) Female",
    languageCode: "nl-NL",
    voiceCode: "nl-NL-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Polish (Poland) Female",
    languageCode: "pl-PL",
    voiceCode: "pl-PL-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Polish (Poland) Male",
    languageCode: "pl-PL",
    voiceCode: "pl-PL-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Polish (Poland) Female",
    languageCode: "pl-PL",
    voiceCode: "pl-PL-3",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Polish (Poland) Female",
    languageCode: "pl-PL",
    voiceCode: "pl-PL-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Portuguese (Brazil) Female",
    languageCode: "pt-BR",
    voiceCode: "pt-BR-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Portuguese (Brazil) Male",
    languageCode: "pt-BR",
    voiceCode: "pt-BR-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Portuguese (Brazil) Male",
    languageCode: "pt-BR",
    voiceCode: "pt-BR-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Portuguese (Brazil) Female",
    languageCode: "pt-BR",
    voiceCode: "pt-BR-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Portuguese (Portugal) Male",
    languageCode: "pt-PT",
    voiceCode: "pt-PT-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Portuguese (Portugal) Female",
    languageCode: "pt-PT",
    voiceCode: "pt-PT-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Portuguese (Portugal) Female",
    languageCode: "pt-PT",
    voiceCode: "pt-PT-3",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Portuguese (Portugal) Female",
    languageCode: "pt-PT",
    voiceCode: "pt-PT-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Romanian (Romania) Female",
    languageCode: "ro-RO",
    voiceCode: "ro-RO-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Romanian (Romania) Male",
    languageCode: "ro-RO",
    voiceCode: "ro-RO-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Romanian (Romania) Male",
    languageCode: "ro-RO",
    voiceCode: "ro-RO-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Russian (Russia) Female",
    languageCode: "ru-RU",
    voiceCode: "ru-RU-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Russian (Russia) Female",
    languageCode: "ru-RU",
    voiceCode: "ru-RU-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Russian (Russia) Male",
    languageCode: "ru-RU",
    voiceCode: "ru-RU-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Russian (Russia) Female",
    languageCode: "ru-RU",
    voiceCode: "ru-RU-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Russian (Russia) Female",
    languageCode: "ru-RU",
    voiceCode: "ru-RU-5",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Russian (Russia) Male",
    languageCode: "ru-RU",
    voiceCode: "ru-RU-6",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Slovak (Slovakia) Male",
    languageCode: "sk-SK",
    voiceCode: "sk-SK-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Slovak (Slovakia) Female",
    languageCode: "sk-SK",
    voiceCode: "sk-SK-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Slovak (Slovakia) Male",
    languageCode: "sk-SK",
    voiceCode: "sk-SK-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Slovenian (Slovenia) Female",
    languageCode: "sl-SI",
    voiceCode: "sl-SI-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Slovenian (Slovenia) Male",
    languageCode: "sl-SI",
    voiceCode: "sl-SI-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Slovenian (Slovenia) Male",
    languageCode: "sl-SI",
    voiceCode: "sl-SI-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Somali (Somalia) Male",
    languageCode: "so-SO",
    voiceCode: "so-SO-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Somali (Somalia) Female",
    languageCode: "so-SO",
    voiceCode: "so-SO-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Sundanese (Indonesia) Male",
    languageCode: "su-ID",
    voiceCode: "su-ID-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Sundanese (Indonesia) Female",
    languageCode: "su-ID",
    voiceCode: "su-ID-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Swedish (Sweden) Female",
    languageCode: "sv-SE",
    voiceCode: "sv-SE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Swedish (Sweden) Female",
    languageCode: "sv-SE",
    voiceCode: "sv-SE-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Swedish (Sweden) Male",
    languageCode: "sv-SE",
    voiceCode: "sv-SE-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Swedish (Sweden) Female",
    languageCode: "sv-SE",
    voiceCode: "sv-SE-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Swahili (Kenya) Male",
    languageCode: "sw-KE",
    voiceCode: "sw-KE-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Swahili (Kenya) Female",
    languageCode: "sw-KE",
    voiceCode: "sw-KE-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Swahili (Tanzania) Male",
    languageCode: "sw-TZ",
    voiceCode: "sw-TZ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Swahili (Tanzania) Female",
    languageCode: "sw-TZ",
    voiceCode: "sw-TZ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Tamil (India) Female",
    languageCode: "ta-IN",
    voiceCode: "ta-IN-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Tamil (India) Male",
    languageCode: "ta-IN",
    voiceCode: "ta-IN-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Tamil (India) Male",
    languageCode: "ta-IN",
    voiceCode: "ta-IN-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Tamil (Sri Lanka) Male",
    languageCode: "ta-LK",
    voiceCode: "ta-LK-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Tamil (Sri Lanka) Female",
    languageCode: "ta-LK",
    voiceCode: "ta-LK-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Tamil (Singapore) Male",
    languageCode: "ta-SG",
    voiceCode: "ta-SG-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Tamil (Singapore) Female",
    languageCode: "ta-SG",
    voiceCode: "ta-SG-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Telugu (India) Male",
    languageCode: "te-IN",
    voiceCode: "te-IN-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Telugu (India) Female",
    languageCode: "te-IN",
    voiceCode: "te-IN-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Telugu (India) Female",
    languageCode: "te-IN",
    voiceCode: "te-IN-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Thai (Thailand) Female",
    languageCode: "th-TH",
    voiceCode: "th-TH-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Thai (Thailand) Female",
    languageCode: "th-TH",
    voiceCode: "th-TH-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Thai (Thailand) Male",
    languageCode: "th-TH",
    voiceCode: "th-TH-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Thai (Thailand) Male",
    languageCode: "th-TH",
    voiceCode: "th-TH-4",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Turkish (Turkey) Male",
    languageCode: "tr-TR",
    voiceCode: "tr-TR-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Turkish (Turkey) Female",
    languageCode: "tr-TR",
    voiceCode: "tr-TR-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Turkish (Turkey) Female",
    languageCode: "tr-TR",
    voiceCode: "tr-TR-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Ukrainian (Ukraine) Male",
    languageCode: "uk-UA",
    voiceCode: "uk-UA-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Ukrainian (Ukraine) Female",
    languageCode: "uk-UA",
    voiceCode: "uk-UA-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Urdu (India) Female",
    languageCode: "ur-IN",
    voiceCode: "ur-IN-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Urdu (India) Male",
    languageCode: "ur-IN",
    voiceCode: "ur-IN-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Urdu (Pakistan) Male",
    languageCode: "ur-PK",
    voiceCode: "ur-PK-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Urdu (Pakistan) Female",
    languageCode: "ur-PK",
    voiceCode: "ur-PK-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Uzbek (Uzbekistan) Female",
    languageCode: "uz-UZ",
    voiceCode: "uz-UZ-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Uzbek (Uzbekistan) Male",
    languageCode: "uz-UZ",
    voiceCode: "uz-UZ-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Vietnamese (Vietnam) Female",
    languageCode: "vi-VN",
    voiceCode: "vi-VN-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Vietnamese (Vietnam) Male",
    languageCode: "vi-VN",
    voiceCode: "vi-VN-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Vietnamese (Vietnam) Male",
    languageCode: "vi-VN",
    voiceCode: "vi-VN-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Male",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-3",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-4",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-5",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-6",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-7",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Male",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-8",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Male",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-9",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-10",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-11",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-12",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-13",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-14",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Male",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-15",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Mandarin, Simplified) Female",
    languageCode: "zh-CN",
    voiceCode: "zh-CN-16",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Cantonese, Traditional) Female",
    languageCode: "zh-HK",
    voiceCode: "zh-HK-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Cantonese, Traditional) Female",
    languageCode: "zh-HK",
    voiceCode: "zh-HK-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Cantonese, Traditional) Male",
    languageCode: "zh-HK",
    voiceCode: "zh-HK-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Cantonese, Traditional) Male",
    languageCode: "zh-HK",
    voiceCode: "zh-HK-4",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Cantonese, Traditional) Female",
    languageCode: "zh-HK",
    voiceCode: "zh-HK-5",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Taiwanese Mandarin) Female",
    languageCode: "zh-TW",
    voiceCode: "zh-TW-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Taiwanese Mandarin) Female",
    languageCode: "zh-TW",
    voiceCode: "zh-TW-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Taiwanese Mandarin) Male",
    languageCode: "zh-TW",
    voiceCode: "zh-TW-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Chinese (Taiwanese Mandarin) Female",
    languageCode: "zh-TW",
    voiceCode: "zh-TW-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Taiwanese Mandarin) Female",
    languageCode: "zh-TW",
    voiceCode: "zh-TW-5",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Chinese (Taiwanese Mandarin) Male",
    languageCode: "zh-TW",
    voiceCode: "zh-TW-6",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Zulu (South Africa) Female",
    languageCode: "zu-ZA",
    voiceCode: "zu-ZA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Zulu (South Africa) Male",
    languageCode: "zu-ZA",
    voiceCode: "zu-ZA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
];
