const data = [
  {
    languageName: "Afrikaans (South Africa) Female",
    languageCode: "af-ZA",
    voiceCode: "af-ZA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Afrikaans (South Africa) Male",
    languageCode: "af-ZA",
    voiceCode: "af-ZA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Amharic (Ethiopia) Male",
    languageCode: "am-ET",
    voiceCode: "am-ET-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Amharic (Ethiopia) Female",
    languageCode: "am-ET",
    voiceCode: "am-ET-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (United Arab Emirates) Female",
    languageCode: "ar-AE",
    voiceCode: "ar-AE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (United Arab Emirates) Male",
    languageCode: "ar-AE",
    voiceCode: "ar-AE-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Bahrain) Male",
    languageCode: "ar-BH",
    voiceCode: "ar-BH-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Bahrain) Female",
    languageCode: "ar-BH",
    voiceCode: "ar-BH-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Algeria) Female",
    languageCode: "ar-DZ",
    voiceCode: "ar-DZ-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Algeria) Male",
    languageCode: "ar-DZ",
    voiceCode: "ar-DZ-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Egypt) Female",
    languageCode: "ar-EG",
    voiceCode: "ar-EG-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Egypt) Male",
    languageCode: "ar-EG",
    voiceCode: "ar-EG-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Egypt) Standard Female",
    languageCode: "ar-EG",
    voiceCode: "ar-EG-3",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Iraq) Male",
    languageCode: "ar-IQ",
    voiceCode: "ar-IQ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Iraq) Female",
    languageCode: "ar-IQ",
    voiceCode: "ar-IQ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Jordan) Female",
    languageCode: "ar-JO",
    voiceCode: "ar-JO-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Jordan) Male",
    languageCode: "ar-JO",
    voiceCode: "ar-JO-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Kuwait) Male",
    languageCode: "ar-KW",
    voiceCode: "ar-KW-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Kuwait) Female",
    languageCode: "ar-KW",
    voiceCode: "ar-KW-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Libya) Female",
    languageCode: "ar-LY",
    voiceCode: "ar-LY-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Libya) Male",
    languageCode: "ar-LY",
    voiceCode: "ar-LY-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Morocco) Male",
    languageCode: "ar-MA",
    voiceCode: "ar-MA-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Morocco) Female",
    languageCode: "ar-MA",
    voiceCode: "ar-MA-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Qatar) Female",
    languageCode: "ar-QA",
    voiceCode: "ar-QA-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Qatar) Male",
    languageCode: "ar-QA",
    voiceCode: "ar-QA-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Saudi Arabia) Male",
    languageCode: "ar-SA",
    voiceCode: "ar-SA-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Saudi Arabia) Female",
    languageCode: "ar-SA",
    voiceCode: "ar-SA-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Saudi Arabia) Standard Male",
    languageCode: "ar-SA",
    voiceCode: "ar-SA-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Syria) Female",
    languageCode: "ar-SY",
    voiceCode: "ar-SY-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Syria) Male",
    languageCode: "ar-SY",
    voiceCode: "ar-SY-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Tunisia) Male",
    languageCode: "ar-TN",
    voiceCode: "ar-TN-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Arabic (Tunisia) Female",
    languageCode: "ar-TN",
    voiceCode: "ar-TN-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Arabic (Yemen) Female",
    languageCode: "ar-YE",
    voiceCode: "ar-YE-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Bulgarian (Bulgaria) Male",
    languageCode: "bg-BG",
    voiceCode: "bg-BG-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Bulgarian (Bulgaria) Female",
    languageCode: "bg-BG",
    voiceCode: "bg-BG-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Bulgarian (Bulgaria) Male",
    languageCode: "bg-BG",
    voiceCode: "bg-BG-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Bangla (Bangladesh) Female",
    languageCode: "bn-BD",
    voiceCode: "bn-BD-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Bangla (Bangladesh) Male",
    languageCode: "bn-BD",
    voiceCode: "bn-BD-2",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Catalan (Spain) Female",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-1",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Catalan (Spain) Female",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Catalan (Spain) Male",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-3",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Catalan (Spain) Female",
    languageCode: "ca-ES",
    voiceCode: "ca-ES-4",
    voiceType: "Standard",
    voiceGender: "Female",
  },
  {
    languageName: "Czech (Czech) Male",
    languageCode: "cs-CZ",
    voiceCode: "cs-CZ-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Czech (Czech) Female",
    languageCode: "cs-CZ",
    voiceCode: "cs-CZ-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
  {
    languageName: "Czech (Czech) Male",
    languageCode: "cs-CZ",
    voiceCode: "cs-CZ-3",
    voiceType: "Standard",
    voiceGender: "Male",
  },
  {
    languageName: "Welsh (United Kingdom) Male",
    languageCode: "cy-GB",
    voiceCode: "cy-GB-1",
    voiceType: "Neural",
    voiceGender: "Male",
  },
  {
    languageName: "Welsh (United Kingdom) Female",
    languageCode: "cy-GB",
    voiceCode: "cy-GB-2",
    voiceType: "Neural",
    voiceGender: "Female",
  },
];
